name: allure-report
on: ["push"]
jobs:
    generate-report:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Download Cypress
              uses: bahmutov/npm-install@v1
              env:
                  CYPRESS_INSTALL_BINARY: 0
            - name: Run E2E Tests
              uses: BerniWittmann/background-server-action@latest
              with:
                build: npm start
                start: php -S 127.0.0.1:8000
                
            - name: lol
              run: curl http://127.0.0.1:8000

            - name: Check Cypress cache
              run: |
                  npx cypress cache path
                  npx cypress cache list
            - name: Install Cypress
              run: |
                  npx cypress install
                  npx cypress cache list
            - name: Run Cypress
              continue-on-error: true
              run: DEBUG=allure-plugin* npx cypress run --env allure=true --browser chrome
              env:
                  CYPRESS_SPLIT_SPEC_API_KEY: '${{ secrets.SPLIT_SPEC_API_KEY }}'

            - name: Get Allure history
              uses: actions/checkout@v2
              if: always()
              continue-on-error: true
              with:
                  ref: allure
                  path: allure

            - name: Generate Allure Report
              uses: simple-elf/allure-report-action@master
              if: always()
              with:
                  allure_results: allure-results
                  gh_pages: allure

            - name: Deploy to GitHub Pages
              id: deployment
              uses: JamesIves/github-pages-deploy-action@4.2.0
              with:
                branch: gh-pages
                folder: ./allure-history
